# ============================== Filebeat inputs ===============================
filebeat.inputs:
  - type: filestream
    id: rasp1-filestream
    enabled: true
    paths:
      - /home/sinterit/logs/*.log
      - /home/sinterit/.Xauthority
      - /home/sinterit/.xsession-errors
      - /var/log/Xorg*.log
      - /home/sinterit_web/.pm2/logs/www*.log
      - /home/sinterit/.pm2/logs/www*.log

monitoring:
  enabled: true
  cluster_uuid: "${CLUSTER_UUID}"
  elasticsearch:
    hosts: ["10.235.207.54:9200", "127.0.0.1:9200", "10.8.0.1:9200"]
    protocol: "https"
    username: "${BEAT_USER:beats_system}"
    password: "${BEAT_PASS:beats_system}"
    ssl.verification_mode: none

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true

#name:

# The tags of the shipper are included in their own field with each
# transaction published.
tags: ["3dprinter"]

# Optional fields that you can specify to add additional information to the
# output.
fields:
  env: prod
  serial: "${SERIAL_NUMBER:noserial}"
  printer_name: "${PRINTER_NAME:noname}"

# ================================== Outputs ===================================

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["10.235.207.54:5044", "127.0.0.1:5044", "10.8.0.1:5044"]
    

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
